import type { Metadata } from "next";
import { Nunito, Lora } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";
import { auth } from "../../auth";

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

const lora = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <body className={`${nunito.variable} ${lora.variable} antialiased`}>
        <NavBar session={session} />
        {children}
      </body>
    </html>
  );
}
